# Cloudflare Pages deployment configuration for HonestInvoice
name = "honestinvoice"
compatibility_date = "2024-08-15"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

# Redirect www to non-www (industry standard)
[[redirects]]
from = "https://www.honestinvoice.com/*"
to = "https://honestinvoice.com/:splat"
status = 301

# SPA routing - must be last
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "preview" }